include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = Client

Client_OBJC_FILES =  \
main.m \
AppController.m \
CustomView.m \

Client_RESOURCE_FILES = Images/* \

-include GNUmakefile.preamble
include $(GNUSTEP_MAKEFILES)/application.make
-include GNUmakefile.postamble

